[book]
title = "mdbook-bookshelf"
description = "Project documentation for mdbook-bookshelf."
language = "en"

[build]
build-dir = ".site"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
additional-js = [".mdbook/mermaid.min.js", ".mdbook/mermaid-init.js"]

[bookshelf]
asset-dir = ".mdbook/bookshelf"

[[bookshelf.book]]
id = "mdbook-bookshelf"
title = "mdbook-bookshelf"
description = "Project documentation for mdbook-bookshelf."
src = "docs"

[[bookshelf.category]]
title = "Project Documentation"
books = ["mdbook-bookshelf"]
